### ISSUE TITLE
Missing "pins" namespace

### ISSUE THREAD

**Issue by AnotherOneAckap** [mihyaeru21/p5-WebService-Slack-WebApi#13]
Would you be so kind to add some more methods for "pins" namespace, as it described in
https://api.slack.com/methods/pins.add
https://api.slack.com/methods/pins.list
https://api.slack.com/methods/pins.remove ?

**Comment by AnotherOneAckap** [comment]
I also made pull request #14 Please take a look on it when you have a minute.

**Comment by mihyaeru21** [comment]
Thank you for PR.
I'll follow latest API, soon.

**Comment by mihyaeru21** [comment]
I released version 0.09 includes `pins` namespace.

Some namespaces aren't included in this version yet.
I will work for remaining namespaces in a few days.
