### ISSUE TITLE
new methos

### ISSUE THREAD

**Issue by mihyaeru21** [mihyaeru21/p5-WebService-Slack-WebApi#16]
https://api.slack.com/methods

**Comment by robin13** [comment]
I specifically wanted to use `users.profile.set` but then found it is not supported.  I was going to implement it, but I'm not sure how you'd want to implement this within the framework you have created... if you give me some pointers I could probably do it.

**Comment by mihyaeru21** [comment]
@robin13 Thank you for your offer.

I've implemented `users.profile` methods in #21 and released `0.13`.
If you need other methods which is not implemented in this library, you can implement like #21.
I welcome your PR 😃

**Comment by robin13** [comment]
@mihyaeru21 Sweet - thank you very much! :)
