### ISSUE TITLE
Please release version 0.14 to cpan

### ISSUE THREAD

**Issue by robin13** [mihyaeru21/p5-WebService-Slack-WebApi#24]
currently only 0.13 is on cpan - could you release the latest version please? :)

**Comment by mihyaeru21** [comment]
@robin13
I'm planning to release the new version as soon as when [this PR](https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/pull/23#pullrequestreview-93814882) was merged. So please correct it.

**Comment by mihyaeru21** [comment]
I published version 0.14 to CPAN with dnd methods.
This is completed by @poptix on #26.
