### ISSUE TITLE
Scim api

### ISSUE THREAD

**Issue by mpapec** [mihyaeru21/p5-WebService-Slack-WebApi#25]
Any hints how to inherit from WebApi package in order to access "Manage people in a workspace"?
 https://api.slack.com/scim
endpoint: https://api.slack.com/scim/v1

Tnx

**Comment by mihyaeru21** [comment]
I suggest to design from scrach.

I designed this module for only Web API. It uses only POST method to simplify core implementation, on the assumption that Web API is a HTTP RPC. However, SCIM API is a REST. HTTP method is meaningful. So I think that inheriting implementation from this module isn't a good way.
