### ISSUE TITLE
Use HTTP::AnyUA instead of Furl (Let user decide which client to use)

### ISSUE THREAD

**Issue by mikkoi** [mihyaeru21/p5-WebService-Slack-WebApi#29]
[HTTP::AnyUA ](https://metacpan.org/pod/HTTP::AnyUA) provides a way to abstract the WWW client out of the code. [Furl](https://metacpan.org/pod/Furl) is a good client, but so are [HTTP::Tiny](https://metacpan.org/pod/HTTP::Tiny) and [LWP::UserAgent](https://metacpan.org/pod/LWP::UserAgent). HTTP::AnyUA would allow the user to decide which client to use. This would be beneficial especially in tight environments where there might be room for only a small client.

**Comment by mihyaeru21** [comment]
That's good idea 👍
Your PR is welcome!

**Comment by mikkoi** [comment]
I did a pull request: https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/pull/37

But we have a problem: all tests which do mocking are failing.

**Comment by mikkoi** [comment]
Completed in commit https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/commit/13f5f0db686f67b6f80ffa9849ef2cb93b98444d
