### ISSUE TITLE
Add Slack method oauth.v2.access

### ISSUE THREAD

**Issue by mikkoi** [mihyaeru21/p5-WebService-Slack-WebApi#38]
https://api.slack.com/methods/oauth.v2.access

But how? `WebService::Slack::WebApi::Oauth::V2`?

**Comment by mihyaeru21** [comment]
Yes. #21 will be helpful. It shows how to implement `users.profile.set`.

**Comment by mikkoi** [comment]
Solved by https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/pulls
I used https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/pull/21 as an example.
Thank you.
