### ISSUE TITLE
WebService::Slack::WebApi::Conversations->open should have channel as an optional attribute

### ISSUE THREAD

**Issue by magudas** [mihyaeru21/p5-WebService-Slack-WebApi#42]
In order to open a direct message conversation, channel has to be empty, and the users attribute can be populate with user id.

**Comment by mikkoi** [comment]
[conversations.open](https://api.slack.com/methods/conversations.open)

**Comment by mikkoi** [comment]
PR https://github.com/mihyaeru21/p5-WebService-Slack-WebApi/pull/44

**Comment by mihyaeru21** [comment]
released on `0.17`
